### ISSUE TITLE
Github access api deprecation notice - access with password

### ISSUE THREAD

**Issue by jmcouffin** [ridleyco/DynaHub#4]
Hi Andrea, 
Just a heads up as I tried Dynhub this morning I recieved this email from github

> On June 10th, 2020 at 08:29 (UTC) you used a password to access an endpoint through the GitHub API using DynaHub (Win32NT 10.0.19041; amd64; fr-FR; Octokit 0.32.0):
> 
> https://api.github.com/user
> 
> Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by Dre-Tas** [comment]
Thanks @jmcouffin ofr the heads up!

I received that email too, now that you remind me.
I'll have to see how [octokit.net](https://github.com/octokit/octokit.net), which is the wrapper for the GitHub APIs that DynaHub uses under the hood, is going to respond to that deprecation.

I'll put it in the list

**Comment by Dre-Tas** [comment]
Actually, now that I'm [reading better](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-passwords), what is going to be deprecated is the login with username and password due to security concerns.

They are suggesting to use only the token workflow (which is already implemented in DynaHub) or, even better, the OAuth workflow, which doesn't exist in DynaHub yet, but I'm willing to implement.
I'll leave the username and password option for now, but I'll get rid of it when it is actually deprecated. In the meantime, **I strongly suggest everyone creates their Personal Access Token and start getting used to it**. It's quite nice and [simple](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)!

I understand in principles how OAuth works but I'm not sure how to implement it so any help is more than welcome!
